import torch.nn as nn
from models.tacotron import DecoderCell

TACOTRON_HP = {
    "encoder_lyric_dim": 256,
    "encoder_pitch_dim": 256,
    "encoder_rhythm_dim": 256,
    "embedding_dim": 256,
    "encoder_n_convolutions": 3,
    "encoder_kernel_size": 5,
    "encoder_p_dropout": 0.5,
    "hidden_dim": 256,
    "attention_dim": 128,
    "attention_rnn_dim": 1024,
    "attention_location_n_filters": 32,
    "attention_location_kernel_size": 31,
    "decoder_rnn_dim": 1024,
    "p_prenet_dropout": 0.1,
    "p_attention_dropout": 0.1,
    "p_decoder_dropout": 0.1,
    "prenet_dim": 128,
    "max_decoder_steps": 1000,
    "stopping_threshold": 0.5,
    "postnet_n_convolutions": 5,
    "postnet_embedding_dim": 512,
    "postnet_kernel_size": 5,
    "postnet_p_dropout": 0.5,
    "decoder_cell": DecoderCell
}

WAVENET_HP = {
    "layers": 10,
    "blocks": 4,
    "in_channels": 1,
    "cond_in_channels": 192,
    "cond_channels": 32,
    "dilation_channels": 32,
    "residual_channels": 32,
    "skip_channels": 256,
    "end_channels": 256,
    "classes": 256,
    "kernel_size": 2,
    "bias": False
}


SODIUM_HP = {
    "embedding_lyric_dim": 256,
    "embedding_pitch_dim": 256,
    "embedding_singer_dim": 16,
    "embedding_technique_dim": 16,
    "encoder_pp_n_fft": 2048,
    "sample_rate": 16000,
    "encoder_pp_num_convolutions": 2,
    "encoder_pp_kernel_size": 3,
    "encoder_pp_num_harmonics": 512,
    "concert_pitch": 440.0,
    "concert_a": 69,
    "encoder_prenet_num_convolutions": 3,
    "encoder_prenet_kernel_size": 5,
    "encoder_prenet_activation": nn.Identity(),
    "encoder_p_dropout": 0.1,
    "encoder_use_transformer": False,
    "encoder_transformer_nlayers": 8,
    "encoder_transformer_nhead": 4,
    "encoder_transformer_ff_dim": 1024,
    "encoder_transformer_activation": "relu",
    "encoder_lstm_num_layers": 1,
    "encoder_lstm_zoneout": 0.1,
    "duration_hidden_dim": 16,
    # "duration_n_layers": 1,
    "duration_bias": False,
    "range_hidden_dim": 256,
    "range_n_layers": 1,
    "range_bias": True,
    "range_clip": 0.1,
    "pos_embedding_dim": 32,
    "pos_embedding_denom": 10000.0,
    "pos_embedding_max_len": 1000,
    "decoder_prenet_n_layers": 2,
    "decoder_prenet_dim": 256,
    "decoder_prenet_activation": nn.ReLU(),
    "decoder_prenet_p_dropout": 0.5,
    "decoder_dim": 1024,
    "decoder_n_layers": 1,
    "output_dim": 192,
    "decoder_zoneout": 0.1,
    "decoder_use_transformer": False,
    "decoder_transformer_nlayers": -1,
    "decoder_transformer_nhead": -1,
    "decoder_transformer_ff_dim": -1,
    "decoder_transformer_activation": "",
    "decoder_transformer_dropout": -1,
    "postnet_num_convolutions": 5,
    "postnet_hidden_features": 512,
    "postnet_kernel_size": 5,
    "postnet_activation": nn.Tanh()
}


SODIUM_LARGE_HP = {
    "embedding_lyric_dim": 512,
    "embedding_pitch_dim": 512,
    "embedding_singer_dim": 32,
    "embedding_technique_dim": 32,
    "encoder_pp_n_fft": 2048,
    "sample_rate": 16000,
    "encoder_pp_num_convolutions": 3,
    "encoder_pp_kernel_size": 5,
    "encoder_pp_num_harmonics": 512,
    "concert_pitch": 440.0,
    "concert_a": 69,
    "encoder_prenet_num_convolutions": 3,
    "encoder_prenet_kernel_size": 5,
    "encoder_prenet_activation": nn.Identity(),
    "encoder_p_dropout": 0.1,
    "encoder_use_transformer": False,
    "encoder_transformer_nlayers": 8,
    "encoder_transformer_nhead": 4,
    "encoder_transformer_ff_dim": 1024,
    "encoder_transformer_activation": "relu",
    "encoder_lstm_num_layers": 2,
    "encoder_lstm_zoneout": 0.1,
    "duration_hidden_dim": 16,
    # "duration_n_layers": 1,
    "duration_bias": False,
    "range_hidden_dim": 512,
    "range_n_layers": 2,
    "range_bias": True,
    "range_clip": 0.1,
    "pos_embedding_dim": 32,
    "pos_embedding_denom": 10000.0,
    "pos_embedding_max_len": 1000,
    "decoder_prenet_n_layers": 2,
    "decoder_prenet_dim": 256,
    "decoder_prenet_activation": nn.ReLU(),
    "decoder_prenet_p_dropout": 0.5,
    "decoder_dim": 1024,
    "decoder_n_layers": 2,
    "output_dim": 192,
    "decoder_zoneout": 0.1,
    "decoder_use_transformer": False,
    "decoder_transformer_nlayers": -1,
    "decoder_transformer_nhead": -1,
    "decoder_transformer_ff_dim": -1,
    "decoder_transformer_activation": "",
    "decoder_transformer_dropout": -1,
    "postnet_num_convolutions": 5,
    "postnet_hidden_features": 512,
    "postnet_kernel_size": 5,
    "postnet_activation": nn.Tanh()
}


SODIUM_RESNET_HP = {
    "use_resnet": True,
    "embedding_lyric_dim": 256,
    "embedding_pitch_dim": 256,
    "embedding_singer_dim": 16,
    "embedding_technique_dim": 16,
    "encoder_pp_n_fft": 2048,
    "sample_rate": 16000,
    "encoder_pp_num_convolutions": 3,
    "encoder_pp_kernel_size": 5,
    "encoder_pp_num_harmonics": 512,
    "concert_pitch": 440.0,
    "concert_a": 69,
    "encoder_prenet_num_convolutions": 3,
    "encoder_prenet_kernel_size": 5,
    "encoder_prenet_activation": nn.Identity(),
    "encoder_p_dropout": 0.1,
    "encoder_use_transformer": False,
    "encoder_transformer_nlayers": -1,
    "encoder_transformer_nhead": -1,
    "encoder_transformer_ff_dim": -1,
    "encoder_transformer_activation": "",
    "encoder_lstm_num_layers": -1,
    "encoder_lstm_zoneout": -1,
    "encoder_resnet_n_layers": 3,
    "encoder_resnet_kernel_size": 5,
    "encoder_resnet_n_hidden_channels": 64,
    "encoder_resnet_activation": nn.ReLU(),
    "encoder_resnet_p_dropout":0.1,
    "duration_hidden_dim": 256,
    "duration_bias": False,
    "range_hidden_dim": 256,
    "range_n_layers": 1,
    "range_bias": True,
    "range_clip": 0.0,
    "pos_embedding_dim": 32,
    "pos_embedding_denom": 10000.0,
    "pos_embedding_max_len": 10000,
    "decoder_prenet_n_layers": -1,
    "decoder_prenet_dim": -1,
    "decoder_prenet_activation": None,
    "decoder_prenet_p_dropout": -1,
    "decoder_dim": -1,
    "decoder_n_layers": -1,
    "output_dim": 192,
    "decoder_zoneout": -1,
    "decoder_use_transformer": False,
    "decoder_transformer_nlayers": -1,
    "decoder_transformer_nhead": -1,
    "decoder_transformer_ff_dim": -1,
    "decoder_transformer_activation": "",
    "decoder_transformer_dropout": -1,
    "decoder_resnet_n_layers": 3,
    "decoder_resnet_kernel_size": 5,
    "decoder_resnet_n_hidden_channels": 64,
    "decoder_resnet_activation": nn.Tanh(),
    "decoder_resnet_p_dropout": 0.1,
    "postnet_num_convolutions": 5,
    "postnet_hidden_features": 256,
    "postnet_kernel_size": 5,
    "postnet_activation": nn.Tanh()
}

SODIUM_TRANSFORMER_HP = {
    "use_resnet": False,
    "embedding_lyric_dim": 256,
    "embedding_pitch_dim": 512,
    "embedding_singer_dim": 16,
    "embedding_technique_dim": 16,
    "encoder_pp_n_fft": 2048,
    "sample_rate": 16000,
    "encoder_pp_num_convolutions": 3,
    "encoder_pp_kernel_size": 5,
    "encoder_pp_num_harmonics": 512,
    "concert_pitch": 440.0,
    "concert_a": 69,
    "encoder_prenet_num_convolutions": 3,
    "encoder_prenet_kernel_size": 5,
    "encoder_prenet_activation": nn.Identity(),
    "encoder_p_dropout": 0.1,
    "encoder_use_transformer": True,
    "encoder_transformer_nlayers": 4,
    "encoder_transformer_nhead": 4,
    "encoder_transformer_ff_dim": 1024,
    "encoder_transformer_activation": "relu",
    "encoder_lstm_num_layers": -1,
    "encoder_lstm_zoneout": -1,
    "encoder_resnet_n_layers": -1,
    "encoder_resnet_kernel_size": -1,
    "encoder_resnet_n_hidden_channels": -1,
    "encoder_resnet_activation": None,
    "encoder_resnet_p_dropout": -1,
    "encoder_output_projection": 256, # to match prenet_dim - pos_embedding_dim
    "duration_hidden_dim": 256,
    # duration_n_layers": 1,
    "duration_bias": False,
    "range_hidden_dim": 256,
    "range_n_layers": 1,
    "range_bias": True,
    "range_clip": 0.1,
    "pos_embedding_dim": 32,
    "pos_embedding_denom": 10000.0,
    "pos_embedding_max_len": 1000,
    "decoder_prenet_n_layers": 2,
    "decoder_prenet_dim": 288,
    "decoder_prenet_activation": nn.ReLU(),
    "decoder_prenet_p_dropout": 0.5,
    "decoder_dim": -1,
    "decoder_n_layers": -1,
    "output_dim": 192,
    "decoder_zoneout": -1,
    "decoder_use_transformer": True,
    "decoder_transformer_nlayers": 8,
    "decoder_transformer_nhead": 4,
    "decoder_transformer_ff_dim": 1024,
    "decoder_transformer_activation": "relu",
    "decoder_transformer_dropout": 0.1,
    "decoder_resnet_n_layers": -1,
    "decoder_resnet_kernel_size": -1,
    "decoder_resnet_n_hidden_channels": -1,
    "decoder_resnet_activation": None,
    "decoder_resnet_p_dropout": -1,
    "postnet_num_convolutions": 5,
    "postnet_hidden_features": 512,
    "postnet_kernel_size": 5,
    "postnet_activation": nn.Tanh()
}